// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repo

import (
	"database/sql"
	"time"
)

type Person struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Surname        string         `json:"surname"`
	Patronymic     sql.NullString `json:"patronymic"`
	PassportNumber int32          `json:"passport_number"`
	PassportSerie  int32          `json:"passport_serie"`
	Address        string         `json:"address"`
}

type Task struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	Description string       `json:"description"`
	StartDt     sql.NullTime `json:"start_dt"`
	EndDt       sql.NullTime `json:"end_dt"`
	CreatedAt   time.Time    `json:"created_at"`
}
